language: node_js
node_js:
- 11
- 10
- 8
- 6
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y gawk jq
jobs:
  include:
    - stage: publish code coverage
      node_js: "8"
      script:
      - yarn test:node:coverage
      - yarn coverage
    - stage: release docs
      if: type != pull_request AND branch = master
      node_js: "8"
      script:
      - yarn generate-docs
      - yarn travis-deploy-github-pages
    - stage: learna publish and npm release
      if: type != pull_request AND tag = true
      node_js: "8"
      script:
        - scripts/publish.sh
sudo: required
dist: xenial
addons:
  chrome: stable
env:
  global:
  - secure: ZKLEofNJCHSzJzfmayPgRdDWqD5N5g7OPs+gJELmwopAKCUaoOH4H5iH0eg1TZzcAoPL/qwU+gheEW1V7Io4PmVB2WUXUdBP9vaqZlrIw/sa6RD/51jpx4MkXd6ciXl1vmiWMnqPBj+S0NuYjKOt1tGMPDiOtK96UUVNA8uRMrs=
  - secure: sAfy698oA7zJdVEYt+MrBFlmbXIC0Xg+PSIA6bc6klp11yfgXS3vIXM5cW4MuijLJhxvPDmGzhsgVHB+pIQXffeVYKQypCp6JcoDG6OyUxUglvHoLaIfpMD+jQzu2I05EFCxyRZWrq+i5tMWZjkUPUfRJrXtnXEYqm2A5cWPOHs=
