language: node_js
node_js:
- lts/*
after_success:
  - npm run coverage
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_BRANCH}" == "master" && npm run deploy-js-doc-to-github
deploy:
  provider: npm
  email: fieldju@gmail.com
  api_key:
    secure: Z4h5kSmH7zEoEEwg6JlrlUxsFOj1ZqY7xoMJuMqWmiNqgWyoXxD9vCKvOSILh1oupiWIgaDFmSifYmPLbbmHWoMHQiwEvH8+rNYgDL3+hS8jm21tI4U4M7URShrPc6yLw1y3cHmNo6JGCZl8x4ZGiAsPw4vQqw0G/+PipMKdBwE=
  on:
    tags: true
    repo: yaorg/node-measured
