language: node_js
node_js:
- lts/*
after_success:
- npm run coverage
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_BRANCH}" == "master"
  && npm run travis-deploy-github-pages
deploy:
  provider: npm
  email: fieldju@gmail.com
  api_key:
    secure: Z4h5kSmH7zEoEEwg6JlrlUxsFOj1ZqY7xoMJuMqWmiNqgWyoXxD9vCKvOSILh1oupiWIgaDFmSifYmPLbbmHWoMHQiwEvH8+rNYgDL3+hS8jm21tI4U4M7URShrPc6yLw1y3cHmNo6JGCZl8x4ZGiAsPw4vQqw0G/+PipMKdBwE=
  on:
    tags: true
    repo: yaorg/node-measured
env:
  global:
    secure: tr3Wo/f/Li3djNmtjMfgFwXQf5Qe3iTuOlDX8OXXFOuH+N1Jc1CMp3kcVt3xq46e2ONwP7d6CQDZomBAKNGKzqJaoD37btnx8ieaOr5bUhWEvtMCvNBQIaEJNv98r6VZBB9MetvrawJyKsQ855TZ+stariZA7AOZPg1Jdje60P4=
